/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDelete: typeof import('./components/ConfirmDelete.vue')['default']
    GoogleMap: typeof import('./components/GoogleMap.vue')['default']
    IoAlert: typeof import('./components/ioAlert.vue')['default']
    IoAutocomplete: typeof import('./components/ioAutocomplete.vue')['default']
    IoImg: typeof import('./components/ioImg.vue')['default']
    PromptInstall: typeof import('./components/PromptInstall.vue')['default']
    PromptUpdate: typeof import('./components/PromptUpdate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeToAgrovilaDialog: typeof import('./components/WelcomeToAgrovilaDialog.vue')['default']
  }
}
