-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 14:18:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beerlivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `beerlivery`;

-- -----------------------------------------------------
-- Schema beerlivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beerlivery` DEFAULT CHARACTER SET utf8 ;
USE `beerlivery`;

-- -----------------------------------------------------
-- Table `beerlivery`.`Tipo_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Tipo_Cliente` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Tipo_Cliente` (
    `id_tipo_cliente` INT NOT NULL,
    `descricao` TEXT NOT NULL,
    `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
    PRIMARY KEY (`id_tipo_cliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `beerlivery`.`Metodo_Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Metodo_Pagamento`;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Metodo_Pagamento` (
    `id_metodo_pagamento` INT NOT NULL,
    `descricao` TEXT NOT NULL,
    `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
    PRIMARY KEY (`id_metodo_pagamento`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `beerlivery`.`Morada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Morada` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Morada` (
    `id_morada` INT NOT NULL AUTO_INCREMENT,
    `linha_endereco1` VARCHAR(45) NOT NULL,
    `linha_endereco2` VARCHAR(45) NULL,
    `codigo_postal` VARCHAR(45) NOT NULL,
    `localidade` VARCHAR(45) NOT NULL,
    `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_morada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Cliente` (
    `id_cliente` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `nif` VARCHAR(9) NULL,
    `email` VARCHAR(45) NULL,
    `telemovel` VARCHAR(15) NOT NULL,
    `data_nascimento` DATE NOT NULL,
    `id_morada` INT NOT NULL,
    `id_tipo_cliente` INT NOT NULL,
    `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
    PRIMARY KEY (`id_cliente`),
    INDEX `fk_Cliente_Morada1_idx` (`id_morada` ASC) VISIBLE,
    INDEX `fk_Cliente_tipo_cliente1_idx` (`id_tipo_cliente` ASC) VISIBLE,
    CONSTRAINT `fk_Cliente_tipo_cliente1`
        FOREIGN KEY (`id_tipo_cliente`)
        REFERENCES `beerlivery`.`Tipo_Cliente` (`id_tipo_cliente`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_Cliente_Morada1`
        FOREIGN KEY (`id_morada`)
        REFERENCES `beerlivery`.`Morada` (`id_morada`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Armazem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Armazem` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Armazem` (
    `id_armazem` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `id_morada` INT NOT NULL,
    `isDeleted` BOOL NOT NULL DEFAULT 0,
    PRIMARY KEY (`id_armazem`),
    INDEX `fk_Armazem_Morada1_idx` (`id_morada` ASC) VISIBLE,
    CONSTRAINT `fk_Armazem_Morada1`
        FOREIGN KEY (`id_morada`)
        REFERENCES `beerlivery`.`Morada` (`id_morada`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Funcionario_Armazem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Funcionario_Armazem` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Funcionario_Armazem` (
  `id_funcionario_armazem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `id_armazem` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_funcionario_armazem`),
  INDEX `fk_funcionario_armazem_Armazem1_idx` (`id_armazem` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_armazem_Armazem1`
    FOREIGN KEY (`id_armazem`)
    REFERENCES `beerlivery`.`Armazem` (`id_armazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Tipo_Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Tipo_Veiculo` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Tipo_Veiculo` (
  `id_tipo_veiculo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_tipo_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_veiculo` INT NOT NULL,
  `quilometragem` INT NULL,
  `combustivel` VARCHAR(45) NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_Veiculo_id_tipo_veiculo_idx` (`id_tipo_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_id_tipo_veiculo`
    FOREIGN KEY (`id_tipo_veiculo`)
    REFERENCES `beerlivery`.`Tipo_Veiculo` (`id_tipo_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Estafeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Estafeta` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Estafeta` (
  `id_estafeta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nr_conducao` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_armazem` INT NOT NULL,
  `id_veiculo` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_estafeta`),
  INDEX `fk_Estafeta_Veiculo1_idx` (`id_veiculo` ASC) VISIBLE,
  INDEX `fk_Estafeta_Armazem1_idx` (`id_armazem` ASC) VISIBLE,
  CONSTRAINT `fk_Estafeta_Armazem1`
    FOREIGN KEY (`id_armazem`)
    REFERENCES `beerlivery`.`Armazem` (`id_armazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estafeta_Veiculo1`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `beerlivery`.`Veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Estado` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Estado` (
  `id_estado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `descricao_estado` TEXT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `beerlivery`.`Encomenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Encomenda` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Encomenda` (
  `id_encomenda` INT NOT NULL AUTO_INCREMENT,
  `distancia` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `data_entrega` DATETIME NULL,
  `custo` FLOAT NOT NULL,
  `id_metodo_pagamento` INT NOT NULL,
  `estado` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_funcionario_armazem` INT NOT NULL,
  `id_estafeta` INT NOT NULL,
  `id_armazem` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_encomenda`),
  INDEX `fk_Ecomenda_Cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_Ecomenda_Funcionario do Armazem1_idx` (`id_funcionario_armazem` ASC) VISIBLE,
  INDEX `fk_Ecomenda_Estafeta1_idx` (`id_estafeta` ASC) VISIBLE,
  INDEX `fk_Ecomenda_Armazem1_idx` (`id_armazem` ASC) VISIBLE,
  INDEX `fk_Encomenda_Estado1_idx` (`estado` ASC) VISIBLE,
  INDEX `fk_Cliente_Metodo_Pagamento_idx` (`id_metodo_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Metodo_Pagamento_idx`
    FOREIGN KEY (`id_metodo_pagamento`)
    REFERENCES `beerlivery`.`Metodo_Pagamento` (`id_metodo_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ecomenda_Cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `beerlivery`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ecomenda_Funcionario do Armazem1`
    FOREIGN KEY (`id_funcionario_armazem`)
    REFERENCES `beerlivery`.`Funcionario_Armazem` (`id_funcionario_armazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ecomenda_Estafeta1`
    FOREIGN KEY (`id_estafeta`)
    REFERENCES `beerlivery`.`Estafeta` (`id_estafeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ecomenda_Armazem1`
    FOREIGN KEY (`id_armazem`)
    REFERENCES `beerlivery`.`Armazem` (`id_armazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encomenda_Estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `beerlivery`.`Estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Marca` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Marca` (
  `id_marca` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(15) NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Categoria` (
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `categoria_mae` INT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categoria_id_categoria_idx` (`categoria_mae` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_id_categoria`
    FOREIGN KEY (`categoria_mae`)
    REFERENCES `beerlivery`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Item` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `item_descricao` TEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `percentagem_alcool` FLOAT NOT NULL,
  `preco` FLOAT NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_item`),
  INDEX `fk_Item_marca1_idx` (`id_marca` ASC) VISIBLE,
  INDEX `fk_Item_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Item_marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `beerlivery`.`Marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `beerlivery`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Encomenda_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Encomenda_Item` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Encomenda_Item` (
  `id_ecomenda` INT NOT NULL,
  `id_item` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_ecomenda`, `id_item`),
  INDEX `fk_Encomenda_has_Item_Item1_idx` (`id_item` ASC) VISIBLE,
  INDEX `fk_Encomenda_has_Item_Encomenda1_idx` (`id_ecomenda` ASC) VISIBLE,
  CONSTRAINT `fk_Encomenda_has_Item_Encomenda1`
    FOREIGN KEY (`id_ecomenda`)
    REFERENCES `beerlivery`.`Encomenda` (`id_encomenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encomenda_has_Item_Item1`
    FOREIGN KEY (`id_item`)
    REFERENCES `beerlivery`.`Item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerlivery`.`Item_Armazem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerlivery`.`Item_Armazem` ;

CREATE TABLE IF NOT EXISTS `beerlivery`.`Item_Armazem` (
  `id_item` INT NOT NULL,
  `id_armazem` INT NOT NULL,
  `stock` INT NOT NULL,
  `isDeleted` BOOL NOT NULL DEFAULT 0,
    `created_on` TIMESTAMP DEFAULT now(),
    `updated_on` TIMESTAMP DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id_item`, `id_armazem`),
  INDEX `fk_Item_Armazem_id_armazem_idx` (`id_armazem` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Armazem_id_item`
    FOREIGN KEY (`id_item`)
    REFERENCES `beerlivery`.`Item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Armazem_id_armazem`
    FOREIGN KEY (`id_armazem`)
    REFERENCES `beerlivery`.`Armazem` (`id_armazem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
